# Change these first
owner: georgewelly # Your GitHub organization or username, where this repository lives
repo: upriseuptime # The name of this repository

sites:
  - name: Uprise Up
    url: https://www.upriseup.co.uk/
  - name: Charity Digital Benchmark
    url: https://www.charitydigitalbenchmark.co.uk/
  - name: Google
    url: https://www.google.com
  #- name: Test Broken Site
  #  url: https://thissitedoesnotexist.koj.co
  - name: Sue Ryder
    url: https://www.sueryder.org/
  - name: Dementia uk  
    url: https://www.dementiauk.org/
  - name: BW site 
    url: https://www.bwcharity.org.uk/
  - name: MSC site
    url: https://www.msc.org/uk
  - name: MSI Choices site
    url: https://www.msichoices.org/
  - name: Royal Voluntary Services
    url: https://www.royalvoluntaryservice.org.uk/
  - name: Ten Health & Fitness  
    url: https://www.ten.co.uk/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  baseUrl: /upriseuptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UpriseUp Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Service tracker for Uprise Up and Charity Digital Benchmark, using upptime.  [**Source repository**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
